name: github-actions
on: [push]
jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - name: decrypt secrets
      - run: streamlit run streamlit_app.py
      env:
        SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
        SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
      