name: github-actions

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: decrypt secrets
        uses: actions/checkout@v2
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
      